include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some overly strict rules for this project
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    use_build_context_synchronously: false